---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: wego-kind-prod1-podinfo-app
  url: ssh://git@github.com/weavegitops/podinfo-app.git

